<% if File.exist?('rubocop_common.yml') %>
inherit_from:
  - rubocop_common.yml
  - .rubocop_todo.yml
<% else %>
inherit_gem:
  rggen-devtools: config/rubocop_common.yml

inherit_from:
  - .rubocop_todo.yml
<% end %>

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  IgnoredMethods:
    - define_value_extractor

Metrics/MethodLength:
  IgnoredMethods:
    - type_map

Naming/VariableNumber:
  AllowedIdentifiers:
    - w1
    - wo1
    - json5
    - load_json5
